spring.application.name=demo
#spring.application.name=RAG
spring.ai.openai.base-url = https://openrouter.ai/api
spring.ai.openai.api-key= ${OPENROUTER_API_KEY}
spring.ai.openai.chat.options.model=nvidia/nemotron-3-super-120b-a12b:free

spring.datasource.url=jdbc:h2:file:./chatpdf-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.sql.init.mode=always

# File upload limits ? allow large PDFs
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Server port
server.port=${PORT:8080}